# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookStack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookStack.proto\x12\tbookStack\"`\n\x08\x42ookdata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x10\n\x08\x62ookname\x18\x03 \x01(\t\x12\x12\n\nbookdescri\x18\x04 \x01(\t\x12\x12\n\nbookimgurl\x18\x05 \x01(\t\"\xf9\x01\n\x10\x43\x61tegoryMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12@\n\x0e\x63\x61tegory_items\x18\x02 \x01(\x0b\x32(.bookStack.CategoryMapEntry.CategoryList\x1a\x95\x01\n\x0c\x43\x61tegoryList\x12P\n\rcategory_list\x18\x01 \x03(\x0b\x32\x39.bookStack.CategoryMapEntry.CategoryList.CategoryListItem\x1a\x33\n\x10\x43\x61tegoryListItem\x12\x0f\n\x07\x63\x61tekey\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"?\n\nCategories\x12\x31\n\x0c\x63\x61tegory_map\x18\x01 \x03(\x0b\x32\x1b.bookStack.CategoryMapEntry\"\x87\x01\n\x06MyData\x12%\n\x08\x62ookdata\x18\x01 \x03(\x0b\x32\x13.bookStack.Bookdata\x12)\n\x08\x63\x61tegory\x18\x02 \x01(\x0b\x32\x15.bookStack.CategoriesH\x00\x12\x0f\n\x05mpage\x18\x03 \x01(\x05H\x01\x42\x0e\n\x0c\x43\x61tegoryDataB\n\n\x08PageDatab\x06proto3')



_BOOKDATA = DESCRIPTOR.message_types_by_name['Bookdata']
_CATEGORYMAPENTRY = DESCRIPTOR.message_types_by_name['CategoryMapEntry']
_CATEGORYMAPENTRY_CATEGORYLIST = _CATEGORYMAPENTRY.nested_types_by_name['CategoryList']
_CATEGORYMAPENTRY_CATEGORYLIST_CATEGORYLISTITEM = _CATEGORYMAPENTRY_CATEGORYLIST.nested_types_by_name['CategoryListItem']
_CATEGORIES = DESCRIPTOR.message_types_by_name['Categories']
_MYDATA = DESCRIPTOR.message_types_by_name['MyData']
Bookdata = _reflection.GeneratedProtocolMessageType('Bookdata', (_message.Message,), {
  'DESCRIPTOR' : _BOOKDATA,
  '__module__' : 'bookStack_pb2'
  # @@protoc_insertion_point(class_scope:bookStack.Bookdata)
  })
_sym_db.RegisterMessage(Bookdata)

CategoryMapEntry = _reflection.GeneratedProtocolMessageType('CategoryMapEntry', (_message.Message,), {

  'CategoryList' : _reflection.GeneratedProtocolMessageType('CategoryList', (_message.Message,), {

    'CategoryListItem' : _reflection.GeneratedProtocolMessageType('CategoryListItem', (_message.Message,), {
      'DESCRIPTOR' : _CATEGORYMAPENTRY_CATEGORYLIST_CATEGORYLISTITEM,
      '__module__' : 'bookStack_pb2'
      # @@protoc_insertion_point(class_scope:bookStack.CategoryMapEntry.CategoryList.CategoryListItem)
      })
    ,
    'DESCRIPTOR' : _CATEGORYMAPENTRY_CATEGORYLIST,
    '__module__' : 'bookStack_pb2'
    # @@protoc_insertion_point(class_scope:bookStack.CategoryMapEntry.CategoryList)
    })
  ,
  'DESCRIPTOR' : _CATEGORYMAPENTRY,
  '__module__' : 'bookStack_pb2'
  # @@protoc_insertion_point(class_scope:bookStack.CategoryMapEntry)
  })
_sym_db.RegisterMessage(CategoryMapEntry)
_sym_db.RegisterMessage(CategoryMapEntry.CategoryList)
_sym_db.RegisterMessage(CategoryMapEntry.CategoryList.CategoryListItem)

Categories = _reflection.GeneratedProtocolMessageType('Categories', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORIES,
  '__module__' : 'bookStack_pb2'
  # @@protoc_insertion_point(class_scope:bookStack.Categories)
  })
_sym_db.RegisterMessage(Categories)

MyData = _reflection.GeneratedProtocolMessageType('MyData', (_message.Message,), {
  'DESCRIPTOR' : _MYDATA,
  '__module__' : 'bookStack_pb2'
  # @@protoc_insertion_point(class_scope:bookStack.MyData)
  })
_sym_db.RegisterMessage(MyData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKDATA._serialized_start=30
  _BOOKDATA._serialized_end=126
  _CATEGORYMAPENTRY._serialized_start=129
  _CATEGORYMAPENTRY._serialized_end=378
  _CATEGORYMAPENTRY_CATEGORYLIST._serialized_start=229
  _CATEGORYMAPENTRY_CATEGORYLIST._serialized_end=378
  _CATEGORYMAPENTRY_CATEGORYLIST_CATEGORYLISTITEM._serialized_start=327
  _CATEGORYMAPENTRY_CATEGORYLIST_CATEGORYLISTITEM._serialized_end=378
  _CATEGORIES._serialized_start=380
  _CATEGORIES._serialized_end=443
  _MYDATA._serialized_start=446
  _MYDATA._serialized_end=581
# @@protoc_insertion_point(module_scope)
