# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08\x64m.proto\x12\x02\x64m\"2\n\x10\x44mSegMobileReply\x12\x1e\n\x05\x65lems\x18\x01 \x03(\x0b\x32\x0f.dm.DanmakuElem\"\x90\x01\n\x0b\x44\x61nmakuElem\x12\r\n\x05\x63olor\x18\x01 \x01(\r\x12\r\n\x05stime\x18\x02 \x01(\x03\x12\x0c\n\x04\x64mid\x18\x03 \x01(\t\x12\x0c\n\x04mode\x18\x04 \x01(\x05\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\r\n\x05uhash\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x08 \x01(\x05\x12\x0e\n\x06weight\x18\t \x01(\x05\x62\x06proto3')

_DMSEGMOBILEREPLY = DESCRIPTOR.message_types_by_name['DmSegMobileReply']
_DANMAKUELEM = DESCRIPTOR.message_types_by_name['DanmakuElem']
DmSegMobileReply = _reflection.GeneratedProtocolMessageType('DmSegMobileReply', (_message.Message,), {
    'DESCRIPTOR': _DMSEGMOBILEREPLY,
    '__module__': 'dm_pb2'
    # @@protoc_insertion_point(class_scope:dm.DmSegMobileReply)
})
_sym_db.RegisterMessage(DmSegMobileReply)

DanmakuElem = _reflection.GeneratedProtocolMessageType('DanmakuElem', (_message.Message,), {
    'DESCRIPTOR': _DANMAKUELEM,
    '__module__': 'dm_pb2'
    # @@protoc_insertion_point(class_scope:dm.DanmakuElem)
})
_sym_db.RegisterMessage(DanmakuElem)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _DMSEGMOBILEREPLY._serialized_start = 16
    _DMSEGMOBILEREPLY._serialized_end = 66
    _DANMAKUELEM._serialized_start = 69
    _DANMAKUELEM._serialized_end = 213
# @@protoc_insertion_point(module_scope)
